version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    links:
      - blackbox:blackbox
      - smokeping:smokeping
      - nodeexp:nodeexp
      - speedtest:speedtest
      - hub:hub
    networks:
      - back-tier

  grafana:
    image: grafana/grafana:7.2.1
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.monitoring
      - ./grafana/auth.env
    restart: always
    networks:
      - back-tier
      - front-tier
 
  hub:
    tty: true
    stdin_open: true
    expose:
      - 19092
    ports:
      - 19092:19092
    restart: always
    image: goddenrich/homehub-metrics-exporter
    env_file:
      - ./hub/auth.env
    networks:
      - back-tier

  blackbox:
    tty: true
    stdin_open: true
    expose:
      - 9115
    ports:
      - 9115:9115
    restart: always
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier

  speedtest:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    ports:
      - 9800:9800
    restart: always
    networks:
      - back-tier
  
  nodeexp:
    privileged: true
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier

  smokeping:
    tty: true
    stdin_open: true
    expose:
      - 9374
    ports:
      - 9374:9374
    restart: always
    image: superque/smokeping-prober:v0.3.1
    command:
      - 'google.com'
      - 'github.com'
    networks:
      - back-tier
