{
 "title": "Home Hub Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "firmware",
    "label": "firmware",
    "query": "label_values(bt_homehub_build_info, firmware)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Firmware version",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<br/>\n<h1><font color=#e68a00><center>$firmware</center></font></h1>"
   },
   "content": "<br/>\n<h1><font color=#e68a00><center>$firmware</center></font></h1>",
   "targets": [
    { "expr": "$firmware" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bt_homehub_uptime_seconds/(60*60*24)"
    }
   ]
  },
  {
   "title": "Upstream sync speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    { "expr": "bt_homehub_upload_rate_mbps" }
   ]
  },
  {
   "title": "Downstream sync speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    { "expr": "bt_homehub_download_rate_mbps" }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Downloaded",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decmbytes", "label": "Per hour" }
   ],
   "targets": [
    {
     "expr": "increase(bt_homehub_device_downloaded_megabytes[1h])",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Uploaded",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decmbytes", "label": "Per hour" }
   ],
   "targets": [
    {
     "expr": "increase(bt_homehub_device_uploaded_megabytes[1h])",
     "legendFormat": "{{host_name}}"
    }
   ]
  }
 ]
}