{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smokeping_response_duration_seconds_bucket, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Download speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second/(1000*1000)"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second/(1000*1000)"
    }
   ]
  },
  {
   "title": "speedtest ping",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "$instance ping loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rate(smokeping_requests_total{host=~\"$instance\"}[10m]) -\nrate(smokeping_response_duration_seconds_count{host=~\"$instance\"}[10m]))/rate(smokeping_response_duration_seconds_count{host=~\"$instance\"}[10m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "$instance ping loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rate(smokeping_requests_total{host=~\"$instance\"}[10m]) -\nrate(smokeping_response_duration_seconds_count{host=~\"$instance\"}[10m]))/rate(smokeping_response_duration_seconds_count{host=~\"$instance\"}[10m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "$instance ping loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(rate(smokeping_requests_total{host=~\"$instance\"}[10m]) -\nrate(smokeping_response_duration_seconds_count{host=~\"$instance\"}[10m]))/rate(smokeping_response_duration_seconds_count{host=~\"$instance\"}[10m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "$instance ping speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$instance ping speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "ping response quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "ping buckets",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$instance ping speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "ping response quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[5m])))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "ping buckets",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(smokeping_response_duration_seconds_bucket{host=~\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}